extent.reporter.spark.start=true
extent.reporter.spark.out=target/extent-report.html

extent.reporter.spark.vieworder=dashboard,test,category,exception,author,device,log

systeminfo.os=Windows
systeminfo.user=Eze